title: Doze Alert
author: Daniel Barnett/Alex Mai/Josh Churchin
email: dbarnet4@u.rochester.edu
description: > # this means to ignore newlines until "baseurl:"
  An app that predicts whether or not you are awake from your brain waves.

twitter_username:
github_username:  danielbarnett714

sass:
    style: compressed