name : Foundation5/github pages/Jykill starter
brand : Doze Alert
description : Doze Alert Description
keyword : 
url : https://danielbarnett714.github.io/DozeAlert/
email : daigo@daigofujiwara.com
twitter : Danielbarnett714
github : Danielbarnett714
author : Daniel Barnett/Alex Mai/Josh Churchin
year : 2017
markdown : kramdown
exclude :
  - node_modules
